# Andy Skabelund
# Assignment 4
# Draws a snowman.
import turtle
tr=turtle.Turtle()
tr.speed(7)
tr.penup()
tr.goto(0, -200)
# Draws 3 circles for the body
tr.color("cyan")
tr.pendown()
tr.circle(100)
tr.penup()
tr.goto(0, 0)
tr.pendown()
tr.circle(75)
tr.penup()
tr.goto(0, 150)
tr.pendown()
tr.circle(50)
tr.penup()
tr.goto(-25, 200)
# Draws and fills eyes
tr.color("black")
tr.begin_fill()
tr.pendown()
tr.circle(12.5)
tr.end_fill()
tr.penup()
tr.goto(25, 200)
tr.color("black")
tr.begin_fill()
tr.pendown()
tr.circle(12.5)
tr.end_fill()
tr.penup()
tr.goto(-20, 185)
# Draws smile
tr.pendown()
tr.setheading(270)
tr.width(10)
tr.circle(20, 180)
tr.penup()
tr.goto(-30, 240)
# Draws and fills hat
tr.begin_fill()
tr.fillcolor("yellow")
tr.pendown()
tr.width(1)
tr.setheading(90)
tr.forward(20)
tr.setheading(180)
tr.forward(20)
tr.setheading(90)
tr.forward(40)
tr.setheading(0)
tr.forward(100)
tr.setheading(270)
tr.forward(40)
tr.setheading(180)
tr.forward(20)
tr.setheading(270)
tr.forward(20)
tr.end_fill()
tr.penup()
tr.goto(-75, 60)
tr.setheading(225)
# Draws stick arms
tr.pendown()
tr.forward(100)
tr.setheading(135)
tr.forward(30)
tr.penup()
tr.goto(-147, -11)
tr.setheading(180)
tr.pendown()
tr.forward(30)
tr.penup()
tr.goto(-147, -11)
tr.setheading(225)
tr.pendown()
tr.forward(30)
tr.penup()
tr.goto(75, 60)
tr.setheading(315)
tr.pendown()
tr.forward(100)
tr.penup()
tr.goto(145, -11)
tr.setheading(45)
tr.pendown()
tr.forward(30)
tr.penup()
tr.goto(145, -11)
tr.setheading(0)
tr.pendown()
tr.forward(30)
tr.penup()
tr.goto(145, -11)
tr.setheading(315)
tr.pendown()
tr.forward(30)
tr.penup()
tr.goto(0, 10)
tr.setheading(0)
# Draws and fills coat buttons
tr.pendown()
tr.begin_fill()
tr.fillcolor("red")
tr.circle(20)
tr.end_fill()
tr.penup()
tr.goto(0, 50)
tr.pendown()
tr.begin_fill()
tr.fillcolor("blue")
tr.circle(20)
tr.end_fill()
tr.penup()
tr.goto(0, 90)
tr.pendown()
tr.begin_fill()
tr.fillcolor("green")
tr.circle(20)
tr.end_fill()
tr.hideturtle()
turtle.done()
